### ISSUE TITLE
CSS Cascading and Inheritance Levels 4 and 5 2021-03-22 > 2021-05-??

### ISSUE THREAD

**Issue by fantasai** [w3c/a11y-request#1]
- CSS Cascading and Inheritance Levels 4 and 5
- https://www.w3.org/TR/css-cascade-4/
- https://www.w3.org/TR/css-cascade-5/
- Note: Cascade 5 is a superset of Cascade 4, so we're sending the review requests together. See https://www.w3.org/TR/css-cascade-5/#additions-l4

- Expect to transition to CR in May/June; depends on HR.
- Previous reviews were against Level 3 (now REC): https://www.w3.org/TR/css-cascade-3/
- Skipped the self-review questionnaire because as far as I can tell, nothing is relevant.
- Please file any issues in https://github.com/w3c/csswg-drafts/issues
- Explainer for Cascade 5's new “cascade layers” feature: see [minutes from Jen Simmons's presentation](https://lists.w3.org/Archives/Public/www-style/2020Feb/0009.html) 

Other comments:

The `revert` keyword introduced in Level 4's [2016 CR publication](https://www.w3.org/TR/2016/CR-css-cascade-4-20160114/#default) allows authors to more easily undo their own styles such that they fall back to the user styles rather than clearing out the user and user-agent origins down to the initial value. This maybe has some slight benefits for accessibility.

Other than that, as far as we can tell, the new features and changes to Cascade since Level 3 do not affect accessibility in any way; they just provide more sophisticated ways for authors to organize their style rules.

Please let us know how long to wait for your review; or if you would prefer to waive detailed a11y review since probably there's not much need for it on this particular spec. :)

**Comment by michael-n-cooper** [comment]
No need to review.
