### ISSUE TITLE
DOM Review Draft — Published 21 June 2021 > 2021-08-31

### ISSUE THREAD

**Issue by siusin** [w3c/a11y-request#10]
- name of spec to be reviewed: DOM Review Draft — Published 21 June 2021
- URL of spec: https://dom.spec.whatwg.org/review-drafts/2021-06/

- What and when is your next expected transition? 2021-08-31, CR
- What has changed since any previous review? Please look at the [list of important changes](https://github.com/w3c/htmlwg/issues/19).
- Where and how to file issues arising? Please file an issue via https://github.com/whatwg/dom/issues.

Other comments:
Thank you!

**Comment by michael-n-cooper** [comment]
@autosponge and @ianpouncey to review.

**Comment by AutoSponge** [comment]
I have no objections to the changes.

**Comment by michael-n-cooper** [comment]
https://www.w3.org/WAI/APA/wiki/DOM_2021-06

Closing as OBE
