### ISSUE TITLE
CSS Masking Module Level 1 2021-08-05 > 2021-11-05

### ISSUE THREAD

**Issue by svgeesus** [w3c/a11y-request#11]
In the issue title above add the document name followed by the date of this request, then the date of your proposed deadline for comments.

- name of spec to be reviewed: CSS Masking Module Level 1
- URL of spec: https://www.w3.org/TR/2021/CRD-css-masking-1-20210805/

- What and when is your next expected transition? CR Snapshot, after wide review
- What has changed since any previous review? [Changes since 2014 CR](https://www.w3.org/TR/2021/CRD-css-masking-1-20210805/#changes)
- Please point to the results of your own self-review (see https://w3c.github.io/apa/fast/checklist.html) [here](https://github.com/w3c/fxtf-drafts/issues/432#issuecomment-893407698)
- Where and how to file issues arising? Please file an issue on the [fxtf repository](https://github.com/w3c/fxtf-drafts/issues)
- Pointer to any explainer for the spec? No separate explainer, but please see [the Introduction](https://www.w3.org/TR/2021/CRD-css-masking-1-20210805/#intro)

Other comments:

**Comment by digilou** [comment]
@svgeesus No accessibility concerns from APA.
