### ISSUE TITLE
CSS Scrollbars 2021-08-29 > 2021-09-30

### ISSUE THREAD

**Issue by frivoal** [w3c/a11y-request#12]
In the issue title above add the document name followed by the date of this request, then the date of your proposed deadline for comments.

- name of spec to be reviewed: CSS Scrollbars Level 1
- URL of spec: https://www.w3.org/TR/css-scrollbars-1/

- What and when is your next expected transition?
   We're planing to go to CR soon, for a loosely defined value of soon. As soon as HR completes, unless something unexpected shows up.
- What has changed since any previous review? I am unsure that there was a previous review for a11y
- Please point to the results of your own self-review (see https://w3c.github.io/apa/fast/checklist.html): https://github.com/w3c/csswg-drafts/issues/6555
- Where and how to file issues arising? https://github.com/w3c/csswg-drafts/labels/css-scrollbars-1
- Pointer to any explainer for the spec? https://github.com/felipeerias/css-scrollbars-explainer

Other comments:

There is one issue relating to a11y that is worth drawing attention to: https://github.com/w3c/csswg-drafts/issues/6351 
There, it was requested that the CSS-WG considers expanding the scrollbar-width property to enable authors to request wide scrollbars, among other things for accessibility reasons. The CSS-WG considered that case, and concluded that while wide scrollbars was a legitimate things for **users** to want, it did not follow that control over this aspect should be given to **authors**. User controls and preferences over UI should be available, but that is a matter of browser settings, not of CSS. Further thoughts are documented in the issue and the minutes attached.

**Comment by johnfoliot** [comment]
***Personal Opinion***

> The CSS-WG considered that case, and concluded that while wide scrollbars was a legitimate things for **users** to want, it did not follow that control over this aspect should be given to **authors**.

Respectfully, if this were the case, then why are you providing a mechanism for the **author** to declare them "thinner"? By currently allowing the author to modify the scrollbar width via this spec, you are only permitting for the scrollbars to be resized (re-width'd?) in one direction (thinner), but not in the 'other' direction (wider - despite both a legitimate use-case and agreement from CSS-WG that this is important for the end user).

```
Name: | scrollbar-width
Value: auto | thin | none
```

Additionally, and perhaps most importantly, **[user-supplied style-sheets](https://developer.mozilla.org/en-US/docs/Web/CSS/Cascade#user_stylesheets)** is a critical consideration for some users with disabilities (low vision, or here reduced mobility/lack of fine motor control), where the end-user is **_also_** the author (of **_their_** necessary custom CSS), and so the mechanism for accommodating **those users** MUST be to allow them to declare the scrollbars wider than what the author proposed.

I _personally_ consider this a BLOCKER for advancing this spec.

**Comment by johnfoliot** [comment]
MyPersonalAccommodationNeeds.css

`body {scrollbar-width: wide!important;}`

**Comment by michael-n-cooper** [comment]
Relates to https://github.com/w3c/a11y-review/issues/85

**Comment by michael-n-cooper** [comment]
Relates to https://github.com/w3c/csswg-drafts/issues/3315

**Comment by michael-n-cooper** [comment]
Issues already under discussion, so no need for generic review.
