### ISSUE TITLE
css-display-3 2021-09-03 > 2021-10-??

### ISSUE THREAD

**Issue by fantasai** [w3c/a11y-request#13]
- name of spec to be reviewed: CSS Display Module Level 3
- URL of spec: https://www.w3.org/TR/css-display-3/

- What and when is your next expected transition?
    - Unknown. Will publish CR Snapshot as soon as HR completes.
- What has changed since any previous review?
    - Copied over `order` property definition from Flexbox. (No change since last a11y review of Flexbox except some editiorial improvements.)
    - Copied over `visibility` property definition from CSS2 and expanded it to explain interactivity and a11y implications.
    - See full Changes list at https://www.w3.org/TR/css-display-3/#changes
    - See Disposition of Comments at https://drafts.csswg.org/css-display-3/issues-cr-2020
- Please point to the results of your own self-review (see https://w3c.github.io/apa/fast/checklist.html)
    - Checklist items don't particularly apply here.
- Where and how to file issues arising?
    - Issues in the [CSSWG repo](https://github.com/w3c/csswg-drafts/issues) with `[css-display]` in the title.
- Pointer to any explainer for the spec?
    - N/A

Other comments:
In terms of what's new and affects a11y, primarily it's the visibility property definition.

**Comment by michael-n-cooper** [comment]
Relates to https://github.com/w3c/csswg-drafts/issues/3040

**Comment by michael-n-cooper** [comment]
https://www.w3.org/WAI/APA/wiki/CSS_Display_Module_Level_3

**Comment by AutoSponge** [comment]
reviewed and accepted
