### ISSUE TITLE
Secure Payment Confirmation (FPWD 2021-08-31)

### ISSUE THREAD

**Issue by ianbjacobs** [w3c/a11y-request#14]
Note that the APA WG prefers groups to run a self-review around the time of FPWD. Let us know when you have done it. Get advice on how to do that at https://w3c.github.io/apa/fast/checklist.html.

If you still want us to review your spec, please provide the information below.

In the issue title above add the document name followed by the date of this request.

- name of spec to be reviewed: Secure Payment Confirmation
- URL of spec: https://w3c.github.io/secure-payment-confirmation/

- Do you need a reply by a particular date? No.
- Please point to the results of your own self-review (see https://w3c.github.io/apa/fast/checklist.html)

NOTE: SPC builds on Web Authentication, so some issues (e.g., accessibility issues associated with biometrics, timeout
associated with Web Authentication prompts, etc.) should be addressed in the underlying specifications.

Having reviewed the self-review checklist, the following points are relevant to SPC capabilities:

* SPC takes an icon as input that is rendered by a native browser modal window. See this issue on icon accessibility:
   https://github.com/w3c/secure-payment-confirmation/issues/127

* See also the accessibility considerations section of the spec regarding modal window accessibility guidelines:
   https://w3c.github.io/secure-payment-confirmation/#sctn-accessibility-considerations

- Where and how to file issues arising?

https://github.com/w3c/secure-payment-confirmation/issues

- Pointer to any explainer for the spec?

https://github.com/w3c/secure-payment-confirmation/blob/main/explainer.md

Other comments:

Thank you! :)

**Comment by michael-n-cooper** [comment]
https://www.w3.org/WAI/APA/wiki/Secure_Payment_Confirmation

**Comment by michael-n-cooper** [comment]
No need to review.
