### ISSUE TITLE
Personalization Semantics Content Module 1.0 2021-09-09 > 2021-10-？

### ISSUE THREAD

**Issue by ruoxiran** [w3c/a11y-request#15]
In the issue title above add the document name followed by the date of this request, then the date of your proposed deadline for comments.

- name of spec to be reviewed: Personalization Semantics Content Module 1.0
- URL of spec: https://w3c.github.io/personalization-semantics/content/

- What and when is your next expected transition? We want to start CR transiton process before November 2021.
- What has changed since any previous review? This working draft is developed by APA WG, and we don't have any a11y review before.
- Where and how to file issues arising?  https://w3c.github.io/personalization-semantics/
- Pointer to any explainer for the spec? https://github.com/w3c/personalization-semantics/issues

**Comment by michael-n-cooper** [comment]
No comments from APA (the publisher).
