### ISSUE TITLE
Incremental Font Transfer 2021-09-14

### ISSUE THREAD

**Issue by svgeesus** [w3c/a11y-request#16]
We have conducted a self-review of our spec [Incremental Font Transfer](Incremental Font Transfer), and the results can be found at [FAST Checklist review for IFT](https://github.com/w3c/IFT/issues/32)

Please check our findings.

- Do you need a reply by a particular date?
No, we just published FPWD

Other comments:

This specification covers transfer of just part of a font, rather than the whole font; and then transferring more as needed behind the scenes. Use of the font is with CSS, same as normal. No other aspect of text rendering is altered; the font just seems to load faster.

**Comment by michael-n-cooper** [comment]
No need to review.

**Comment by svgeesus** [comment]
The [FAST checklist review](https://github.com/w3c/IFT/issues/32) for this working draft are the same as previously.

**Comment by svgeesus** [comment]
Reminder, any comments on IFT from an A11y perspective?
