### ISSUE TITLE
CSS Custom Properties for Cascading Variables Module Level 1 2021-11-11 > 2022-01-11

### ISSUE THREAD

**Issue by svgeesus** [w3c/a11y-request#18]
- name of spec to be reviewed: **CSS Custom Properties for Cascading Variables Module Level 1** but you can call it "CSS Variables" like everyone else 
- URL of spec: https://www.w3.org/TR/2021/CRD-css-variables-1-20211111/

- What and when is your next expected transition? CR Snapshot, after wide review is complete
- What has changed since any previous review? [Changes since 2015 CR](https://www.w3.org/TR/2021/CRD-css-variables-1-20211111/#changes-20151203)
- Please point to the results of your own self-review (see https://w3c.github.io/apa/fast/checklist.html) [self review](https://github.com/w3c/csswg-drafts/issues/6808#issuecomment-965394913)
- Where and how to file issues arising? In the [CSS WG repo, please](https://github.com/w3c/csswg-drafts)
- Pointer to any explainer for the spec? No, but [the two paragraphs of introduction](https://www.w3.org/TR/2021/CRD-css-variables-1-20211111/#intro) are helpful and also [here is a quick tutorial](https://www.freecodecamp.org/news/learn-css-variables-in-5-minutes-80cf63b4025d/)

Other comments:

**Comment by michael-n-cooper** [comment]
No comments from APA.
