### ISSUE TITLE
IMSC-HRM 2021-12-07

### ISSUE THREAD

**Issue by himorin** [w3c/a11y-request#19]
We have conducted a self-review of our spec [IMSC-HRM](https://www.w3.org/TR/imsc-hrm/) ([ED](https://w3c.github.io/imsc-hrm/spec/imsc-hrm.html)), and the results can be found at [IMSC-HRM self check result](https://github.com/w3c/imsc-hrm/issues/17).

Please check our findings.

- Do you need a reply by a particular date? : no particular date (expecting standard period like 2mo, but understand there is long holidays within)

Other comments: 

- we expect no much change from FPWD, and wiling to enter CR relatively shortly without large number of  substantive changes
- original text was in TTML-IMSC specification, and cutted HRM section out for easier maintenance and upgrade

**Comment by michael-n-cooper** [comment]
https://www.w3.org/WAI/APA/wiki/IMSC_Hypothetical_Render_Model

**Comment by himorin** [comment]
diff from initial text (cut out from existing IMSC 1.2 spec) to current text:
https://services.w3.org/htmldiff?doc1=https%3A%2F%2Fraw.githubusercontent.com%2Fw3c%2Fimsc-hrm%2F694ab17c5b8d571db74529689e41b23453c3b6f8%2Fspec%2Fimsc-hrm.html&doc2=https%3A%2F%2Fraw.githubusercontent.com%2Fw3c%2Fimsc-hrm%2Fmain%2Fspec%2Fimsc-hrm.html

**Comment by michael-n-cooper** [comment]
Closing review request in light of filed comment https://github.com/w3c/imsc-hrm/issues/23
