### ISSUE TITLE
CSS Multi-column Layout Module Level 1 2021-04-01 > 2021-05-01

### ISSUE THREAD

**Issue by rachelandrew** [w3c/a11y-request#2]
- CSS Multi-column Layout Module Level 1
- https://www.w3.org/TR/css-multicol-1/
- I hope to transition to CR in May or June depending on results of HR.
- No previous review I am aware of.
- See below for self review
- Please file any issues in https://github.com/w3c/csswg-drafts/issues 

Other comments:

This specification was in CR, and was moved back to WD status after a long period of no updates. It is well implemented already in browsers and print user agents.

From an accessibility standpoint the main issue with use of multicol is that lengthy fragmented content on the web can be difficult to read due to a need to scroll to see the top of the next column. 

### If technology allows visual rendering of content

- **There is a defined way for a non-visual rendering to be created:** Multicol maintains the normal flow and semantics of content, fragmenting it for visual rendering but not changing anything about the underlying document.
- **Content can be resized:** Multicol does not prevent a user resizing the text. It would be possible for an author to make the reading experience harder with large text by columns ending up with a very few words on them. However this is the case with all layout methods if fixed sizes are used. Authors can use column sizes that relate to content size (for example `em`) to avoid this problem.
- **Luminosity and hue contrast can adapt to user requirements.** n/a
- **Text presentation attributes can be changed.** as with resizing content multicol does restrict line length, which could make content harder to read in certain circumstances.
- **Visual presentation of pointers and cursors can be adjusted.** n/a
- **Changing content presentation does not render it unreadable.** multicol should not cause content to be clipped or become unreadable.
- **Technology does not allow blinking or flashing of content, or provides a feature for users to quickly turn it off or permanently disable it.** n/a
- **It is possible to make navigation order correspond to the visual presentation:** navigation order in multicol follows the normal flow of the document, and the columns in normal reading order. Columns cannot be switched around away from that order.

The rest of the checkpoints do not apply to multicol. 

This is my first request for review, let me know if I have missed anything and I welcome any questions or issues raised against the spec.

**Comment by digilou** [comment]
@rachelandrew I will look over this and run it past APA for discussion, as well. Ideally, we'll have a response for you before May.

**Comment by becka11y** [comment]
The above comments have been added into the CSS github repository at https://github.com/w3c/csswg-drafts/issues/6283, and labeled as a11y-needs-resolution.
