### ISSUE TITLE
CSS Conditional 4 2022-01-14 > 2022-03-14

### ISSUE THREAD

**Issue by svgeesus** [w3c/a11y-request#20]
n the issue title above add the document name followed by the date of this request, then the date of your proposed deadline for comments.

- name of spec to be reviewed: **CSS Conditional Rules Module Level 4**
- URL of spec: [https://www.w3.org/TR/css-conditional-4/](https://www.w3.org/TR/css-conditional-4/)

- What and when is your next expected transition?
  - Candidate Recommendation
- What has changed since any previous review?
  - Since the [previous horizontal review of CSS Conditional 3](https://github.com/w3c/csswg-drafts/issues/5569) one new feature has been added, as described below.
- Please point to the results of your own self-review (see https://w3c.github.io/apa/fast/checklist.html)
  - Nothing in the FAST checklist seemed to apply to this very small delta specification
- Where and how to file issues arising?
  - As an [issue in our GitHub, please](https://github.com/w3c/csswg-drafts/labels/css-conditional-4)
- Pointer to any explainer for the spec?
  - [Explainer for `selector()` in `@supports`](https://github.com/dbaron/css-supports-functions/blob/main/explainer.md) by L. David Baron

Other comments:

This is currently a delta specification to [CSS Conditional 3](); the plan is to copy in all of that spec into this one, but currently this very short spec just has the one new feature relative to Level 3.

CSS Conditional 3 already has the ability to test whether CSS properties and property values are supported, before using them. This specification adds the ability to test of Selectors as well.

This specification, currently a Working Draft, is being advanced to CR soon because [all modern browsers now support it](https://caniuse.com/mdn-css_at-rules_supports_selector)

The published /TR specification does not have an example. Sorry! The [explainer](https://github.com/dbaron/css-supports-functions/blob/main/explainer.md) does, and one was also [just added to the ED](https://drafts.csswg.org/css-conditional-4/) plus test suite coverage. Apart from that, the /TR and ED are identical.

**Comment by michael-n-cooper** [comment]
https://www.w3.org/WAI/APA/wiki/CSS_Conditional_Rules_Module_Level_4

**Comment by AutoSponge** [comment]
reviewed and accepted
