### ISSUE TITLE
W3C Baggage 2022-04-26 (Requesting FPWD review)

### ISSUE THREAD

**Issue by kalyanaj** [w3c/a11y-request#22]
Note that the APA WG prefers groups to run a self-review around the time of FPWD. Let us know when you have done it. Get advice on how to do that at https://w3c.github.io/apa/fast/checklist.html.

If you still want us to review your spec, please provide the information below.

In the issue title above add the document name followed by the date of this request.

- name of spec to be reviewed: W3C Baggage
- URL of spec: https://www.w3.org/TR/baggage/

- Do you need a reply by a particular date? Yes, we are planning to get to CR in the coming few months.
- Please point to the results of your own self-review (see https://w3c.github.io/apa/fast/checklist.html): https://github.com/w3c/baggage/issues/94
- Where and how to file issues arising? https://github.com/w3c/baggage/issues/
- Pointer to any explainer for the spec?  https://github.com/w3c/baggage/blob/main/baggage/README.md provides an overview and the use cases.

Other comments:

**Comment by michael-n-cooper** [comment]
https://www.w3.org/WAI/APA/wiki/Propagation_format_for_distributed_trace_context:_Baggage

APA says no need to review, and no need to complete FAST checklist.
