### ISSUE TITLE
Web Neural Network API 2022-05-10 > 2022-09-01

### ISSUE THREAD

**Issue by anssiko** [w3c/a11y-request#26]
- Name of spec to be reviewed: Web Neural Network API
- URL of spec: https://www.w3.org/TR/webnn/

- What and when is your next expected transition? CR in Q4 2022.
- What has changed since any previous review? This is the first formal a11y review request.
- Please point to the results of your own self-review: https://github.com/webmachinelearning/webnn/issues/261
- Where and how to file issues arising? https://github.com/webmachinelearning/webnn/issues
- Pointer to any explainer for the spec? https://github.com/webmachinelearning/webnn/blob/main/explainer.md

Other comments:

The Web Machine Learning WG working on this specification has received review and contributions from a11y experts. @michael-n-cooper has contributed to the companion document [Ethical Principles for Web Machine Learning](https://webmachinelearning.github.io/ethical-webmachinelearning/) to help integrate a11y perspective and the [W3C Workshop on Web and Machine Learning](https://www.w3.org/2020/06/machine-learning-workshop/presentations.html) had multiple presentations on accessibility topics by experts that informed this WG's work and scoping of this API.

Please also see the [use cases](https://www.w3.org/TR/webnn/#usecases) this API enables that have accessibility improvement potential, for example, image captioning, noise suppression, and video summarization.

Thank you for your review!

**Comment by michael-n-cooper** [comment]
https://www.w3.org/WAI/APA/wiki/Web_Neural_Network_API

**Comment by anssiko** [comment]
@michael-n-cooper, please let us know if you have any questions that would help facilitate your review. We have made available the WG's input to the a11y checklist https://github.com/webmachinelearning/webnn/issues/261 you may find helpful.

**Comment by michael-n-cooper** [comment]
Adding @jasonjgw who APA assigned to review this. Jason, see the previous comment for context.

**Comment by jasonjgw** [comment]
Having briefly reviewed the specification, I concur with the Web Machine Learning Working Group's self-assessment. 
Furthermore, section 5 of the draft cites Ethical Principles for Web Machine Learning, which in turn notes the relevance of disability and accessibility issues to the appropriate application of machine learning techniques. I think this cross-reference to the ethical principles is important and valuable, even in a technical API specification, as it raises awareness among users of the API.

Given the range of moral and policy issues raised by the technology, a general reference to the companion document which addresses these matters in detail is, in my view, welcome and appropriate.

**Comment by anssiko** [comment]
@jasonjgw thank you for your review and comments. I infer APA is satisfied with the specification and supports the WG's approach to discuss disability and accessibility issues in the context of its ethics deliverable that is linked from the technical specification.

Please let us know if APA is planning to conduct further review by the review period end (2022-09-01), otherwise I'll thank you again on behalf of the WG and inform the WG the a11y review has been completed with support for the work.

**Comment by anssiko** [comment]
@jasonjgw, I'm marking the a11y review as completed in the WebML WG's wide review tracker https://github.com/webmachinelearning/webnn/issues/239. Feel free to close this issue.

Thanks to the whole group for your review. Should you have further comments, our WG is always happy to allocate time to discuss with you.

**Comment by michael-n-cooper** [comment]
APA done.

**Comment by anssiko** [comment]
Hi again APA!

NB: I'm piggypacking on this issue to retain context. Based on our self-assessment there are no new a11y issues since your previous review, so please consider this for your information only, not a formal review request.

We're looking to publish a new CR Snapshot of the [Web Neural Network API](https://www.w3.org/TR/webnn/) in Q1'24 and wanted to give you a heads up with the following high-level summary of changes for your information and review:

>Since the [initial Candidate Recommendation Snapshot](https://www.w3.org/TR/2023/CR-webnn-20230330/) the Working Group has gathered further [implementation experience](https://webmachinelearning.github.io/webnn-status/) and added new operations and data types needed for well-known [transformers to support generative AI use cases](https://github.com/webmachinelearning/webnn/issues/375). In addition, the group has removed select features informed by this implementation experience: higher-level operations that can be expressed in terms of lower-level primitives in a performant manner, and support for synchronous execution. The group has also updated the specification to use modern authoring conventions to improve interoperability and precision of normative definitions and is developing a new feature, a [backend-agnostic storage type](https://github.com/webmachinelearning/webnn/issues/482), to improve performance and interoperability between the WebNN, WebGPU APIs and purpose-built hardware for ML.

We continue to evaluate our work using your Accessibility Checklist, with our latest status tracked in https://github.com/webmachinelearning/webnn/issues/261

**Comment by matatk** [comment]
Hi @anssiko; we didn't see this one, due to the issue being closed, so sorry for the delay. Thanks for describing the changes you have made. We do not think there is a need for us to re-review - we're pleased the link to the Ethical Principles for Web Machine Learning.

Sounds like this work is progressing well; all the best. If there are any significant changes in future, please let us know (the best way would be to file a new issue, and link back to this one).
