### ISSUE TITLE
MiniApp Lifecycle 2022-05-11 > 2022-08-11

### ISSUE THREAD

**Issue by xfq** [w3c/a11y-request#27]
In the issue title above add the document name followed by the date of this request, then the date of your proposed deadline for comments.

- name of spec to be reviewed: MiniApp Lifecycle
- URL of spec: https://www.w3.org/TR/miniapp-lifecycle/

- What and when is your next expected transition? CR in August 2022
- What has changed since any previous review? This is the first formal a11y review request.
- Please point to the results of your own self-review (see https://w3c.github.io/apa/fast/checklist.html) https://github.com/w3c/miniapp-lifecycle/issues/23
- Where and how to file issues arising? https://github.com/w3c/miniapp-lifecycle/issues
- Pointer to any explainer for the spec? https://github.com/w3c/miniapp-lifecycle/blob/main/docs/explainer.md

Other comments:

See also the [MiniApp Standardization White Paper](https://www.w3.org/TR/mini-app-white-paper/).

**Comment by michael-n-cooper** [comment]
https://www.w3.org/WAI/APA/wiki/MiniApp_Lifecycle
