### ISSUE TITLE
MiniApp Manifest 2022-05-12 > 2022-08-12

### ISSUE THREAD

**Issue by xfq** [w3c/a11y-request#28]
In the issue title above add the document name followed by the date of this request, then the date of your proposed deadline for comments.

- name of spec to be reviewed: MiniApp Manifest
- URL of spec: https://www.w3.org/TR/miniapp-manifest/

- What and when is your next expected transition? CR in August 2022
- What has changed since any previous review? This is the first formal a11y review request.
- Please point to the results of your own self-review (see https://w3c.github.io/apa/fast/checklist.html) https://github.com/w3c/miniapp-manifest/issues/49
- Where and how to file issues arising? https://github.com/w3c/miniapp-manifest/issues
- Pointer to any explainer for the spec? https://github.com/w3c/miniapp-manifest/blob/main/docs/explainer.md

Other comments:

See also the [MiniApp Standardization White Paper](https://www.w3.org/TR/mini-app-white-paper/).

**Comment by michael-n-cooper** [comment]
https://www.w3.org/WAI/APA/wiki/MiniApp_Manifest @ruoxiran to review

**Comment by michael-n-cooper** [comment]
Janina to also review.
