### ISSUE TITLE
CSS Color 5 2022-05-20 > 2022-08-20

### ISSUE THREAD

**Issue by svgeesus** [w3c/a11y-request#29]
- name of spec to be reviewed: CSS Color Module Level 5
- URL of spec: https://drafts.csswg.org/css-color-5/ or https://www.w3.org/TR/2022/WD-css-color-5-20220428/

- What and when is your next expected transition? Moving to CR around Q3 2022
- What has changed since any previous review? Has not previously had a11y review
- Please point to the results of your own self-review (see https://w3c.github.io/apa/fast/checklist.html): (nothing in [FAST](https://w3c.github.io/apa/fast/checklist.html) seemed relevant)
- Where and how to file issues arising? On [CSSWG repo](https://github.com/w3c/csswg-drafts/issues/) please
- Pointer to any explainer for the spec? Please see [theIntroduction](https://drafts.csswg.org/css-color-5/#intro)

Other comments:

CSS WG would like to draw your attention in particular to [the `color-contrast()` function](https://drafts.csswg.org/css-color-5/#colorcontrast) which automatically calculates the color (from a list of candidate colors) with the highest WCAG 2.1 luminance contrast. 

CSS WG is aware of the existing work to produce a better contrast metric; applauds this work, and hopes to reference it as an option in the `color-contrast()` function when consensus has formed and the calculation has stabilized. Meanwhile though, and despite the known limitations of the WCAG 2.1 luminance contrast formula, this is the one we are referencing for now.

**Comment by svgeesus** [comment]
Note that a **Formal Objection** to CSS Color 4 `color-contrast()` referencing the W3C Recommendation WCAG 2.1 Color Contrast [has been raised](https://github.com/w3c/csswg-drafts/issues/7310#issuecomment-1146693305) by @myndex

For further details on possible resolution, please see
https://github.com/w3c/csswg-drafts/issues/7297#issuecomment-1146819748

**Comment by svgeesus** [comment]
Note that the `color-contrast()` function was moved to CSS Color 6, and thus no longer forms part of CSS Color 5. We believe this resolves the formal objection.

Are there any A11y comments on the rest of the specification?

We are trying to deal with all issues on this specification, in preparation for moving to CR.

**Comment by Myndex** [comment]
The only thing I'd like to mention, that we've been discussing in terms of making normative, is that any site that uses a color space other than sRGB must also support sRGB as a default.

I could see this expanded to "only sRGB and display P3".

The two biggest concerns for color spaces and accessibility are the position of the RED primary, and the dynamic range/mapping of the dynamic range related to text and semantic non-text content.


### What I *think* this implies is the need for a media query such as "prefers sRGB"
or some means of fallback to sRGB values.

I also tend to think that at this time, it would be challenging to develop visual accessibility guidelines that accurately encompassed the breadth of color spaces permitted in CSS 5, and arguably, accessibility guidelines are best constrained to cases that relate to physically realizable display tecnologies.

**Comment by svgeesus** [comment]
> accessibility guidelines are best constrained to cases that relate to physically realizable display tecnologies.

I think some confusion exists here; for accessibility, what matters is the display. For specifying color, it is perfectly fine to have imaginary primaries like ProPhoto or indeed CIE XYZ. These are quite separate concepts. There is no display on the market that takes OK L, a and b as inputs. But OKLab works great for things like computing color gradients.

This is why I would prefer to see APCA explicitly state that the equations are modelling a reference sRGB-like display and that Ys is the luminance of that display.

**Comment by Myndex** [comment]
Hi Chris @svgeesus 

I understand I may not be in touch with scope/context of this thread, so my further comments might not belong here, I'll be very brief:

> _This is why I would prefer to see APCA explicitly state that the equations are modelling a reference sRGB-like display and that Ys is the luminance of that display._

It does state this, BUT... as I think you have noticed I have a documentation problem that is an ongoing priority task among a lot of priority tasks... 😳


> ..._for accessibility, what matters is the display..._

So, what I have been considering lately is, for WCAG guidelines, a very simplified set of minimums, citing sRGB as the reference display (possibly adding in P3 as an option).

But then the more complete guidelines/system as a separate (not WCAG) guideline, as I outline in this post at the incubator: [Visual Contrast and Readability methods and guidelines](https://github.com/WICG/proposals/issues/55) which would be a superset of the simplified minimums.

This might be a good discussion sometime for a zoom call...

**Comment by matatk** [comment]
@svgeesus: APA has no accessibility concerns regarding the substance of [CSS Color Module Level 5](https://www.w3.org/TR/2022/WD-css-color-5-20220628/) (we reviewed the 2022-06-28 WD).

It's clear that a lot of effort has gone into making the document readable and understandable. However, we did notice some accessibility barriers, particularly from the perspective of readers who may struggle with color perception. These concerns, with suggestions, are being filed as issues on the CSSWG tracker.

We're aware that `color-contrast()` has been pushed back to Level 6. However, we were wondering what are the use cases for this function? The function selects from a pre-determined list of colours; are there situations in which the answer could not have been determined at design time? We don't feel that this function is required in order to further accessibility, but we're happy to provide any needed support in adding it, if you wish to add it or something similar in future. [The `color-contrast()` function is on our agenda for TPAC](https://www.w3.org/WAI/APA/wiki/Meetings/TPAC_2022#CSS_.26_APA_Joint_Meeting) and we'd be happy to learn more about, and discuss this more there.

*[APA WG consensus decision on this and our other comments](https://lists.w3.org/Archives/Public/public-apa-admin/2022Aug/0055.html)*

**Comment by svgeesus** [comment]
> It's clear that a lot of effort has gone into making the document readable and understandable. However, we did notice some accessibility barriers, particularly from the perspective of readers who may struggle with color perception. These concerns, with suggestions, are being filed as issues on the CSSWG tracker.

Thanks for taking the time to point these out, I am going through and addressing them one by one.

**Comment by svgeesus** [comment]
> We're aware that color-contrast() has been pushed back to Level 6.

Yes. Lets discuss that on an appropriately-tagged issue, so that the discussion does not get lost in this one. Happy to discuss at TPAC, also.

**Comment by michael-n-cooper** [comment]
https://github.com/w3c/csswg-drafts/issues/7730

**Comment by michael-n-cooper** [comment]
[breadcrumbs to minutes of TPAC discussion](https://www.w3.org/WAI/APA/wiki/Meetings/TPAC_2022#CSS_.26_APA_Joint_Meeting)

**Comment by AutoSponge** [comment]
I'm tracking this discussion as well as related discussions like https://github.com/w3c/csswg-drafts/issues/7358

**Comment by AutoSponge** [comment]
We want to update AGWG about the ongoing conversation.

**Comment by svgeesus** [comment]
A reminder that this issue is for A11y review of CSS Color 5 before it moves to CR.

The meta-issue for [tracking the development of `contrast-color()`, which is in CSS Color 6, is here](https://github.com/w3c/csswg-drafts/issues/7553)

**Comment by svgeesus** [comment]
So, given there were no substantive comment on the specification, and the accessibility barriers (thanks for raising those issues) are all addressed, could this be closed @michael-n-cooper @matatk  ?

**Comment by matatk** [comment]
Agreed @svgeesus, this can be closed (I'm not able to, but if you are, you're welcome to.)

Thanks again for your quick fixes on the presentational accessibility issues we raised.
