### ISSUE TITLE
Requesting review of accessibility issue in CSS Color Adjust 2021-05-13 -> 2021-06-24

### ISSUE THREAD

**Issue by fantasai** [w3c/a11y-request#3]
This is a request for a11y review of a specific issue and its proposed resolution.

- name of spec to be reviewed: CSS Color Adjust Level 1
- URL of spec: https://www.w3.org/TR/css-color-adjust-1/

* Issue to be reviewed: https://github.com/w3c/csswg-drafts/issues/5710
* Specific comment containing our response to be reviewed: https://github.com/w3c/csswg-drafts/issues/5710#issuecomment-840772752
* Previous Accessibility Review request: <https://lists.w3.org/Archives/Public/public-apa/2020Nov/0004.html> (currently no response)
* Overall feature definition is the intersection of <https://drafts.csswg.org/css-color-adjust/#forced> and <https://drafts.csswg.org/css-color-4/#css-system-colors>

Please file any responses as comments on the linked issue. Thanks~

**Comment by michael-n-cooper** [comment]
Amy to review.

**Comment by digilou** [comment]
@fantasai Sorry this didn't get to you. [Reviewed in January](https://github.com/w3c/css-a11y/issues/36#issuecomment-759162880). We see forced colors in favor of the user a good thing. @michael-n-cooper

**Comment by fantasai** [comment]
@digilou Thanks for the link to the overall spec review! I updated our HR tracker for the spec. :)

The specific issue resolution identified in this issue still needs an a11y position, though, I think.

**Comment by michael-n-cooper** [comment]
[APA wiki tracking](https://www.w3.org/WAI/APA/wiki/CSS_Multi-column_Layout_Module_Level_1)

**Comment by michael-n-cooper** [comment]
No comments, satisfied with issue dispositions.
