### ISSUE TITLE
DCAT 3 2022-05-10

### ISSUE THREAD

**Issue by riccardoAlbertoni** [w3c/a11y-request#31]
We have conducted a self-review of our spec [DCAT 3](https://www.w3.org/TR/vocab-dcat-3/), and the results can be found at https://github.com/w3c/dxwg/issues/1506.

Please check our findings.

- Do you need a reply by a particular date?
End of August, Early September as we plan to move to CR in Autumn.

**Comment by michael-n-cooper** [comment]
No need for APA to review, did so in the past. https://www.w3.org/WAI/APA/wiki/Data_Catalog_Vocabulary_(DCAT)_-_Version_3
