### ISSUE TITLE
WebXR AR Module Level 1 2021-05-27 > 2021-07-27

### ISSUE THREAD

**Issue by himorin** [w3c/a11y-request#32]
In the issue title above add the document name followed by the date of this request, then the date of your proposed deadline for comments.

- name of spec to be reviewed: WebXR Augmented Reality Module - Level 1
- URL of spec: https://www.w3.org/TR/2022/WD-webxr-ar-module-1-20220426/

- What and when is your next expected transition? as soon as HR finished
- What has changed since any previous review? this is first review request
- Please point to the results of your own self-review (see https://w3c.github.io/apa/fast/checklist.html) https://github.com/immersive-web/webxr-ar-module/issues/84
- Where and how to file issues arising? https://github.com/immersive-web/webxr-ar-module/issues
- Pointer to any explainer for the spec? https://github.com/immersive-web/webxr-ar-module/blob/main/ar-module-explainer.md

Other comments:

**Comment by michael-n-cooper** [comment]
https://www.w3.org/WAI/APA/wiki/WebXR_Augmented_Reality_Module_-_Level_1

**Comment by himorin** [comment]
hi @michael-n-cooper , thank you for update as comment. Looking at wiki page, it states `2021-08-25: No need to review.`, and is it ok to take this as review completed, or any further procedure in a11y group?

**Comment by michael-n-cooper** [comment]
Hi @himorin - the [apa discussion](https://www.w3.org/2022/06/01-apa-minutes#t09) was inconclusive. Since we didn't wind up assigning someone to review it, I will interpret that we still don't need to review this one, and that APA activity on WebXR is currently focused on other modules.
