### ISSUE TITLE
VISS 2 Core and Transport documents  2022-08-31 > 2022-09-30

### ISSUE THREAD

**Issue by caribouW3** [w3c/a11y-request#38]
In the issue title above add the document name followed by the date of this request, then the date of your proposed deadline for comments.

- name of spec to be reviewed:
VISS 2 Core, VISS 2 Transport

- URL of spec:
https://www.w3.org/TR/viss2-core/
https://www.w3.org/TR/viss2-transport/

- What and when is your next expected transition?
End of september

- What has changed since any previous review?
no previous review available

- Please point to the results of your own self-review (see https://w3c.github.io/apa/fast/checklist.html)
VISS 2 does not specify any user interface nor anything that manipulates user-facing data (it is mostly a
protocol spec). It defines some access control feature but nothing that would seem to affect accessibility of
tools or further specs that would make use of VISS2. 

- Where and how to file issues arising?
https://github.com/w3c/automotive

- Pointer to any explainer for the spec?
https://github.com/w3c/automotive/blob/gh-pages/viss2-explainer.md

Other comments:

Thanks!

**Comment by michael-n-cooper** [comment]
[APA discussed](https://www.w3.org/2022/09/07-apa-minutes.html#t04), no need to review Transport, still working on getting review complete for Core. [APA tracking](https://www.w3.org/WAI/APA/wiki/VISS_version_2_-_Core)

**Comment by michael-n-cooper** [comment]
[APA decided it won't deliver a review](https://www.w3.org/2022/09/28-apa-minutes#t08), so no comments pending from APA on either spec.
