### ISSUE TITLE
Resource Timing 2021-06-02 > 2021-06-23

### ISSUE THREAD

**Issue by caribouW3** [w3c/a11y-request#4]
- name of spec to be reviewed: Resource Timing

- URL of spec: https://w3c.github.io/resource-timing/

- What and when is your next expected transition?
w3c/transitions#337 (comment)
Wide review was done in 2017. The Director is requesting a formal wide review with the most recent horizontal review process.

- What has changed since any previous review?
In comparison to previously published "level 1" (in CR), changes are mainly
the addition of the size attributes, better buffering algorithms and Fetch integration.
We plan to drop levels and use a living standard development model (from process2020).

- Please point to the results of your own self-review (see https://w3c.github.io/apa/fast/checklist.html)
This specification relies on APIs, the API can't be used for structured content, the API does not rely on 
user agents to generate a user interface.

- Where and how to file issues arising?
https://github.com/w3c/resource-timing/issues/

- Pointer to any explainer for the spec?
https://w3c.github.io/resource-timing/#introduction

**Comment by michael-n-cooper** [comment]
No comments from APA.
