### ISSUE TITLE
CSS Values and Units Level 4 2021-10-19 > 2021-01-31

### ISSUE THREAD

**Issue by fantasai** [w3c/a11y-request#41]
- name of spec to be reviewed: CSS Values and Units Level 4
- URL of spec: https://www.w3.org/TR/css-values-4/

- What and when is your next expected transition? to CR, sometime after we resolve some open issues on url() and the viewport units
- What has changed since any previous review? No previous formal review
- Please point to the results of your own self-review (see https://w3c.github.io/apa/fast/checklist.html) None applicable!
- Where and how to file issues arising? https://github.com/w3c/csswg-drafts/issues tagged [css-values-4]
- Pointer to any explainer for the spec? None

Other comments:

The most interesting part of this specification from an accessibility perspective is the length units https://www.w3.org/TR/css-values-4/#lengths which allow authors to size things relative to the text or the viewport as well as absolutely.

There is a list of changes since Level 3 at https://www.w3.org/TR/css-values-4/#additions-L3

This specification is feature-frozen; new feature requests are now going into Level 5.

**Comment by ruoxiran** [comment]
tracking at: https://www.w3.org/WAI/APA/wiki/CSS_Values_and_Units_Module_Level_4

**Comment by ruoxiran** [comment]
no issue raise from APA review.
