### ISSUE TITLE
CSS View Transitions 2022-11-20

### ISSUE THREAD

**Issue by khushalsagar** [w3c/a11y-request#44]
Name of spec to be reviewed: CSS View Transitions

URL of spec: https://www.w3.org/TR/css-view-transitions-1/

Do you need a reply by a particular date? No

Please point to the results of your own self-review: See comments below

Where and how to file issues arising? https://github.com/w3c/csswg-drafts/issues tagged [css-view-transitions-1]

Pointer to any explainer for the spec: https://github.com/WICG/view-transitions/blob/main/explainer.md

Other comments:

CSS View Transitions allows authors to create animations when switching between DOM states. The DOM change can be synchronous from the web author's perspective. The UA caches a visual representation of the previous which is displayed via pseudo-elements. These pseudo-elements can be targeted by the web developer to create custom animations.

For an a11y review of this draft, there are 2 areas where we would appreciate feedback:

- Since the transition is meant to be a purely visual enhancement, the pseudo-elements used for it are ignored when populating the AX tree. The AX tree is built using the current DOM state and has the same output when no transition is initiated by the author.
- Authors can create transitions with patterns the can be disorienting to users who prefer reduced motion. We advise authors to use the existing [prefers-reduced-motion](https://w3c.github.io/csswg-drafts/mediaqueries-5/#prefers-reduced-motion) media query to avoid animations or limit them to cross-fades. However there is no explicit removal of functionality if the user has opted-in to reduced motion. A discussion on this issue is captured [here](https://github.com/WICG/view-transitions/issues/19).

Thank you.

**Comment by ruoxiran** [comment]
tracking at: https://www.w3.org/WAI/APA/wiki/CSS_View_Transitions_Module_Level_1

**Comment by AutoSponge** [comment]
reviewed and accepted
