### ISSUE TITLE
UI Events Keyboard Event Key Values 2022-11-29 2023-01-31

### ISSUE THREAD

**Issue by LJWatson** [w3c/a11y-request#47]
- name of spec to be reviewed: UI Events Keyboard Events Key Values
- URL of spec: https://w3c.github.io/uievents-key/
- What and when is your next expected transition? to CR, ASAP
- What has changed since any previous review?
- Please point to the results of your own self-review (see https://w3c.github.io/apa/fast/checklist.html) https://github.com/w3c/uievents-key/issues/57#issuecomment-1301231347
- Where and how to file issues arising? https://github.com/w3c/uievents-key/issues/
- Pointer to any explainer for the spec?

Other comments:

**Comment by ruoxiran** [comment]
Fredrik to review, tracking at: https://www.w3.org/WAI/APA/wiki/UI_Events_KeyboardEvent_key_Values

**Comment by LJWatson** [comment]
In this [email to public-apa](https://lists.w3.org/Archives/Public/public-apa/2023Jan/0001.html) Fredrik asked if this spec should apply to braille and other alternative input devices. To the best of my knowledge all alternative input devices utilise standard key codes and values, so they're implicitly covered by these specifications already.

If APA agrees, we'd welcome your confirmation that there are o issues arising from your review.

With thanks.

**Comment by matatk** [comment]
APA is happy to sign off on this.

With reference to the discussion on list and in our calls, we ultimately felt those concerns were addressed in the documents via the introduction and accessibility considerations sections—thanks!
