### ISSUE TITLE
UI Events Keyboard Events Code Values 2022-11-29 2023-01-31

### ISSUE THREAD

**Issue by LJWatson** [w3c/a11y-request#48]
- Name of spec to be reviewed: UI Events Keyboard Events Code Values
- URL: https://w3c.github.io/uievents-code/
- Next transition: to CR, February 2023
- Accessibility considerations: https://w3c.github.io/uievents-code/#accessibility
Self-review: https://github.com/w3c/uievents-code/issues/35#issuecomment-1301296494
- File issues: https://github.com/w3c/uievents-key/issues/

**Comment by ruoxiran** [comment]
Fredrik to review, tracking at: https://www.w3.org/WAI/APA/wiki/UI_Events_KeyboardEvent_code_Values

**Comment by LJWatson** [comment]
In this [email to public-apa](https://lists.w3.org/Archives/Public/public-apa/2023Jan/0001.html) Fredrik asked if this spec should apply to braille and other alternative input devices. To the best of my knowledge all alternative input devices utilise standard key codes and values, so they're implicitly covered by these specifications already.

If APA agrees, we'd welcome your confirmation that there are o issues arising from your review.

With thanks.

**Comment by matatk** [comment]
APA is happy to sign off on this.

With reference to the discussion on list and in our calls, we ultimately felt those concerns were addressed in the documents via the introduction and accessibility considerations sections—thanks!
