### ISSUE TITLE
User Timing 2021-06-02 > 2021-06-23

### ISSUE THREAD

**Issue by caribouW3** [w3c/a11y-request#5]
- name of spec to be reviewed: User Timing 
- URL of spec: https://w3c.github.io/user-timing/ 

- What and when is your next expected transition? 
https://github.com/w3c/transitions/issues/338#issuecomment-850636248
Wide review was already done for level 2. The WG wants to drop levels and merge level 3 in it.
The Director is requesting a formal wide review with the most recent horizontal review process.

- What has changed since any previous review? 
In level 3, addition of ability to execute marks and measures across arbitrary timestamps and
support for reporting arbitrary metadata along with marks and measures.

- Please point to the results of your own self-review (see https://w3c.github.io/i18n-drafts/techniques/shortchecklist)
This specification relies on APIs, there is no natural language exposed, no text, no localization.

- Where and how to file issues arising?
https://github.com/w3c/user-timing/issues/
 
- Pointer to any explainer for the spec? 
https://w3c.github.io/user-timing/#introduction

**Comment by michael-n-cooper** [comment]
No comments from APA.
