### ISSUE TITLE
Secure Payment Confirmation 2023-01-11 > 2023-02-01

### ISSUE THREAD

**Issue by ianbjacobs** [w3c/a11y-request#50]
- name of spec to be reviewed: Secure Payment Confirmation (SPC)
- URL of spec:  https://w3c.github.io/secure-payment-confirmation/

- What and when is your next expected transition? Candidate Recommendation
- What has changed since any previous review?

In August 2022 the Web Payments Working Group requested [1] pre-Candidate Recommendation horizontal review of Secure Payment Confirmation (SPC). All reviews led to satisfactory outcomes. Thank you for your review.

Since then, the Web Payments Working Group has made or plans to make two non-editorial changes to the specification for which we seek additional horizontal review:

* The addition of an opt-out feature, requested by developers to help  satisfy GDPR requirements. For background, see issue 172 [1] and the resulting changes to the specification [2]. Experimentation with this feature has demonstrated its utility to at least one organization that has experimented with SPC.
* The expected removal of a requirement that the user agent consume a user activation during authentication. For background, see issue 216 [3], including the Chrome Team's security and privacy consideration notes. Although we have not yet updated the specification to remove the user activation requirement, we seek your review at this time. We would anticipate the actual change to the specification to be small (and it would include the security and privacy considerations).

[1] https://github.com/w3c/secure-payment-confirmation/issues/172
[2] https://github.com/w3c/secure-payment-confirmation/pull/215
[3] https://github.com/w3c/secure-payment-confirmation/issues/216

- Please point to the results of your own self-review (see https://w3c.github.io/apa/fast/checklist.html)

We created our previous checklist in August 2022; we have updated it for this review request:
 https://github.com/w3c/secure-payment-confirmation/blob/main/accessibility-checklist.md

- Where and how to file issues arising? https://github.com/w3c/secure-payment-confirmation/issues/
- Pointer to any explainer for the spec? https://github.com/w3c/secure-payment-confirmation/blob/main/explainer.md

**Comment by ianbjacobs** [comment]
Hi all,

I wanted to check to see whether you have this request on an upcoming agenda. Thank you,

Ian

**Comment by matatk** [comment]
Hi @ianbjacobs. APA is happy to sign off on spec. Thanks for your review request, and we look forward to continuing to work with you in future. (Feel free to close this issue if you are able to.)

**Comment by ianbjacobs** [comment]
Thank you @matatk and APA!
