### ISSUE TITLE
Web Content Accessibility Guidelines (WCAG) 2.2 2023-01-30 > 2023-02-24

### ISSUE THREAD

**Issue by michael-n-cooper** [w3c/a11y-request#52]
### Name of your specification

Web Content Accessibility Guidelines (WCAG) 2.2

### URL of your specification

https://www.w3.org/TR/2023/CRD-WCAG22-20230125/

### When does the review need to be finished?

2023-02-24

### What has changed since any previous review?

https://www.w3.org/TR/WCAG22/#substantive-changes-since-the-6-september-2022-candidate-recommendation

### Where and how should the i18n WG raise issues?

https://github.com/w3c/wcag/issues/

**Comment by matatk** [comment]
Hi all. APA is happy to sign off on this; good work!

Thanks also to Fredrik in our group for looking into this too.
