### ISSUE TITLE
Digital Publishing WAI-ARIA Module 1.1 and Digital Publishing Accessibility API Mappings 1.1 2023-02-23 > 2023-04-01

### ISSUE THREAD

**Issue by mattgarrish** [w3c/a11y-request#55]
- Name of spec to be reviewed:
  - Digital Publishing WAI-ARIA Module 1.1
  - Digital Publishing Accessibility API Mappings 1.1
- URL of spec:
  - https://www.w3.org/TR/2023/WD-dpub-aria-1.1-20230222/
  - https://www.w3.org/TR/2023/WD-dpub-aam-1.1-20230223/
- What and when is your next expected transition?
  - Moving to CR, ideally in April
- What has changed since any previous review?
  - Refer to the change logs for updates since the 1.0 release: https://www.w3.org/TR/2023/WD-dpub-aria-1.1-20230222/#changelog and https://www.w3.org/TR/2023/WD-dpub-aam-1.1-20230223/#changelog
- Please point to the results of your own self-review
  - As these documents are extensions of ARIA and Core-AAM, they do not introduce new unique accessibility issues. 
- Where and how to file issues arising?
  - Please open issues for the DPUB-ARIA spec in https://github.com/w3c/dpub-aria/issues and issues for the DPUB-AAM in https://github.com/w3c/dpub-aam/issues
- Pointer to any explainer for the spec?
  - https://www.w3.org/TR/2023/WD-dpub-aria-1.1-20230222/#introduction

**Comment by ruoxiran** [comment]
no comment or request from APA WG.

**Comment by mattgarrish** [comment]
Thanks for the review @ruoxiran!
