### ISSUE TITLE
Scalable Video Coding (SVC) Extension for WebRTC 2023-04-25 > 2023-05-16

### ISSUE THREAD

**Issue by dontcallmedom** [w3c/a11y-request#57]
In the issue title above add the document name followed by the date of this request, then the date of your proposed deadline for comments.

- name of spec to be reviewed: Scalable Video Coding (SVC) Extension for WebRTC
- URL of spec: https://www.w3.org/TR/2023/WD-webrtc-svc-20230417/
- What and when is your next expected transition? mid May 2023 to CR

- What has changed since any previous review? https://github.com/w3c/webrtc-svc/pulls?q=is%3Apr+is%3Aclosed+merged%3A%3E%3D2020-05-01+-label%3AEditorial+ ([previous review request](https://lists.w3.org/Archives/Public/public-apa/2020Apr/0013.html))
- Please point to the results of your own self-review (see https://w3c.github.io/apa/fast/checklist.html)
> From my reading of http://w3c.github.io/apa/fast/checklist.html, and given that this specification mostly deals with codec negotiation, I don't believe there are any particular accessibility concerns
- Where and how to file issues arising? https://github.com/w3c/webrtc-svc/issues
- Pointer to any explainer for the spec? https://github.com/w3c/webrtc-svc/blob/main/explainer.md

**Comment by ruoxiran** [comment]
tracking: https://www.w3.org/WAI/APA/wiki/Scalable_Video_Coding_(SVC)_Extension_for_WebRTC

**Comment by ruoxiran** [comment]
APA is OK with this document going to CR.
