### ISSUE TITLE
CSS Counter Styles 2021-06-03 > 2021-06-30

### ISSUE THREAD

**Issue by fantasai** [w3c/a11y-request#6]
In the issue title above add the document name followed by the date of this request, then the date of your proposed deadline for comments.

- name of spec to be reviewed: CSS Counter Styles L3
- URL of spec: https://drafts.csswg.org/css-counter-styles-3/#changes-2017 (hopefully by the time you read this, the spec will have been regenerated with a "Changes since the 2017 CR" section)

- What and when is your next expected transition? CRS soon-ish
- What has changed since any previous review? see changes list above
- Please point to the results of your own self-review nothing new/interesting
- Where and how to file issues arising? https://github.com/w3c/csswg-drafts/issues including [css-counter-styles-3] in the subject line
- Pointer to any explainer for the spec? none

Other comments:

Only one change seems related to a11y; the diffs for that are called out in the changes section.

**Comment by michael-n-cooper** [comment]
@digilou and @lseeman to review.

**Comment by michael-n-cooper** [comment]
[APA wiki tracking](https://www.w3.org/WAI/APA/wiki/CSS_Counter_Styles_Level_3)

**Comment by michael-n-cooper** [comment]
No comments from APA.
