### ISSUE TITLE
Verifiable Credential Data Integrity (and vc-di-eddsa and vc-di-ecdsa) 2023-05-27 -> 2023-07-31

### ISSUE THREAD

**Issue by msporny** [w3c/a11y-request#61]
- Name of specs to be reviewed:
  * [Verifiable Credential Data Integrity](https://www.w3.org/TR/vc-data-integrity/)
  * [EdDSA Cryptosuite v2022](https://www.w3.org/TR/vc-di-eddsa/)
  * [ECDSA Cryptosuite v2019](https://www.w3.org/TR/vc-di-ecdsa/)

- URL of specs:
  * [Verifiable Credential Data Integrity](https://www.w3.org/TR/vc-data-integrity/)
  * [EdDSA Cryptosuite v2022](https://www.w3.org/TR/vc-di-eddsa/)
  * [ECDSA Cryptosuite v2019](https://www.w3.org/TR/vc-di-ecdsa/)

- What and when is your next expected transition?
  - Transition to Candidate Recommendation in September 2023 (at W3C TPAC)
- What has changed since any previous review?
  - There has bee no previous review of these specifications
- Please point to the results of your own self-review (see https://w3c.github.io/apa/fast/checklist.html)
  - https://github.com/w3c/vc-data-integrity/issues/97 
- Where and how to file issues arising?
  - https://github.com/w3c/vc-data-integrity/issues
- Pointer to any explainer for the spec?
  - https://www.w3.org/TR/vc-data-integrity/#introduction

Other comments:

The three specifications listed above are cryptographic message securing mechanisms and thus do not contain text, visuals, audio, or haptic data that will be experienced directly by a human being. The one exception for this is possibly software developers, who might encounter error messages when using software libraries that implement the specification above. The errors have specific codes, which are internationalizable, but whose internationalization characteristics are up to each implementer.

We believe that these specifications, in general, do not create accessibility concerns, but are curious to know if we have overlooked some aspect of how these technologies will be used that will create accessibility issues.

**Comment by matatk** [comment]
@msporny: thanks for your review request; APA has no accessibility concerns.

[minutes from today's call on this review request](https://www.w3.org/2023/07/26-apa-minutes.html#t06)

**Comment by matatk** [comment]
@ruoxiran: Do we have a wiki page for long-term tracking for this spec?

**Comment by msporny** [comment]
> @msporny: thanks for your review request; APA has no accessibility concerns.

Thank you for the review, APA, much appreciated!
