### ISSUE TITLE
Verifiable Credentials Data Model v2.0 2021-06-15

### ISSUE THREAD

**Issue by awoie** [w3c/a11y-request#65]
We have conducted a self-review of our spec [Verifiable Credentials Data Model v2.0](https://www.w3.org/TR/vc-data-model-2.0/), and the results can be found at https://github.com/w3c/vc-data-model/issues/1156

Please check our findings.

**Comment by matatk** [comment]
APA wiki page: https://www.w3.org/WAI/APA/wiki/Verifiable_Credentials_Data_Model_v2.0

**Comment by awoie** [comment]
Thank you very much for your time and the review.
