### ISSUE TITLE
BBS Cryptosuite v2023 2023-12-15 2024-01-15

### ISSUE THREAD

**Issue by Wind4Greg** [w3c/a11y-request#69]
In the issue title above add the document name followed by the date of this request, then the date of your proposed deadline for comments.

- name of spec to be reviewed: BBS Cryptosuite v2023 Securing Verifiable Credentials with Selective Disclosure
using BBS Signatures

- URL of spec: https://www.w3.org/TR/vc-di-bbs/

- What and when is your next expected transition? 
  Transition to Candidate Recommendation in January 2024
  
- What has changed since any previous review? 
  No previous review
- Please point to the results of your own self-review (see https://w3c.github.io/apa/fast/checklist.html)
  https://github.com/w3c/vc-di-bbs/issues/102

- Where and how to file issues arising?
  https://github.com/w3c/vc-di-bbs/issues
- Pointer to any explainer for the spec?
  https://www.w3.org/TR/vc-di-bbs/#introduction
Other comments:

**Comment by ruoxiran** [comment]
Matthew reviewed it at: https://github.com/w3c/vc-di-bbs/issues/102#issuecomment-1881461695

**Comment by matatk** [comment]
Quick update on this thread (being the thread for APA WG's response): I just filed [one more question on the self-review thread](https://github.com/w3c/vc-di-bbs/issues/102#issuecomment-1904181644) (thanks for providing that info), on which confirmation would be great. Aside from that, we don't have any other accessibility concerns.

Just one caveat, that we're not experts in cryptography (but we know you are!); we've been looking for any areas that may expose info to the end user.
