### ISSUE TITLE
Performance Timeline 2021-06-07 > 2021-06-28

### ISSUE THREAD

**Issue by caribouW3** [w3c/a11y-request#7]
- name of spec to be reviewed: Performance Timeline
- URL of spec: https://w3c.github.io/performance-timeline/

- What and when is your next expected transition? 
https://github.com/w3c/transitions/issues/339#issuecomment-850639142
Wide review was done in 2016 for its previous CR.
The Director is requesting a formal wide review with the most recent horizontal review process.

- What has changed since any previous review? 
Previous CR was https://www.w3.org/TR/2016/CR-performance-timeline-2-20161208/
There is no fundamental change to the goals of the spec. The processing model is more detailed and 
data structure updated.
We plan to drop levels and use a living standard development model (from process2020).

- Please point to the results of your own self-review (see https://w3c.github.io/apa/fast/checklist.html)
This specification relies on APIs, the API can't be used for structured content, the API does not rely on
user agents to generate a user interface.

- Where and how to file issues arising?
https://github.com/w3c/performance-timeline/

**Comment by michael-n-cooper** [comment]
@frederika11y will review.

**Comment by michael-n-cooper** [comment]
No comments from APA.
