### ISSUE TITLE
Pointer Events Level 3 2024-03-30 > 2024-06-12

### ISSUE THREAD

**Issue by patrickhlauke** [w3c/a11y-request#78]
- name of spec to be reviewed: Pointer Events Level 3
- URL of spec: https://www.w3.org/TR/pointerevents3/

- What and when is your next expected transition? We're hoping to move to CR over the summer
- What has changed since any previous review? See the revision history https://www.w3.org/TR/pointerevents3/#revision-history
- Please point to the results of your own self-review (see https://w3c.github.io/apa/fast/checklist.html): as far as we are aware, due to the nature of the specification/API (which deals exclusively with pointer events at a low level), none of the FAST checkpoints are applicable
- Where and how to file issues arising? https://github.com/w3c/pointerevents/issues
- Pointer to any explainer for the spec? https://www.w3.org/TR/pointerevents3/#intro

**Comment by matatk** [comment]
Apologies for the late response. APA does not have any concerns about this work, and we are happy to see it move forward.

We may have some editorial suggestions in future - we'll file those as issues in your repo in due course if so.

*[minutes from APA call on which we last discussed the spec](https://www.w3.org/2024/06/19-apa-minutes#t08)*
