### ISSUE TITLE
MediaStream Image Capture 2021-06-22 > 2021-07-22

### ISSUE THREAD

**Issue by caribouW3** [w3c/a11y-request#8]
In the issue title above add the document name followed by the date of this request, then the date of your proposed deadline for comments.

- name of spec to be reviewed: MediaStream Image Capture
- URL of spec: https://w3c.github.io/mediacapture-image/

- What and when is your next expected transition? not yet defined
- What has changed since any previous review? this is a 1st review
- Please point to the results of your own self-review (see https://w3c.github.io/apa/fast/checklist.html)
This specification is purely an API without impact on a user interface
- Where and how to file issues arising?
https://github.com/w3c/mediacapture-image
- Pointer to any explainer for the spec?
https://github.com/w3c/mediacapture-image/blob/main/explainer.md

Other comments:

**Comment by michael-n-cooper** [comment]
[APA wiki tracking](https://www.w3.org/WAI/APA/wiki/MediaStream_Image_Capture)

**Comment by michael-n-cooper** [comment]
No comments from APA.
