### ISSUE TITLE
Device Posture API 2024-05-31 > 2024-08-31

### ISSUE THREAD

**Issue by anssiko** [w3c/a11y-request#84]
- name of spec to be reviewed: Device Posture API
- URL of spec: https://www.w3.org/TR/device-posture/

- Current Rec/Note phase? Working Draft
- What and when is your next expected transition? We expect to publish new Working Drafts in the short term. We will assess the readiness for the CR transition when the Origin Trial feedback has been received from early adopters in Q4 2024.
- What has changed since any previous review? This is the first formal a11y review request. That said, the specification was reviewed by an APA WG member Paul Grenier in April 2021 https://github.com/w3c/device-posture/issues/70 that resulted in an [Accessibility considerations](https://www.w3.org/TR/device-posture/#accessibility-considerations) section being added to the specification.
- Please point to the results of your [self-review](https://w3c.github.io/apa/fast/checklist.html) https://github.com/w3c/device-posture/issues/147
- Where and how to file issues arising? https://github.com/w3c/device-posture/issues/147
- Pointer to any explainer for the spec? [Device Posture API explainer](https://github.com/w3c/device-posture/blob/gh-pages/README.md) (for additional material, see [Form Factors explainer](https://webscreens.github.io/form-factors/) for the broader domain and [Foldable APIs Origin Trial](https://developer.chrome.com/blog/foldable-apis-ot) for a developer-oriented explainer)

Other comments:

The Device Posture API is available as an [Origin Trial](https://developer.chrome.com/origintrials/#/view_trial/4188910603407982593) from Chrome 125 until 128. See [Origin trial for Foldable APIs](https://developer.chrome.com/blog/foldable-apis-ot) for a developer-oriented article on how this JS API and CSS primitives work together.

[foldable-devices/demos](https://github.com/foldable-devices/demos) hosts demos of various use cases for the API.

Thank you APA WG for your contributions that resulted in the Accessibility considerations. We are happy to answer any further questions you may have and look forward to your review.

**Comment by AutoSponge** [comment]
Well done. No comments from APA.

**Comment by anssiko** [comment]
Thank you again APA for your swift review with special thanks to @AutoSponge for contributing the [accessibility considerations](https://www.w3.org/TR/device-posture/#accessibility-considerations) section!

I've updated our wide review tracker https://github.com/w3c/device-posture/issues/146 acknowledging a11y review has been completed.
