### ISSUE TITLE
Vibration API 2024-06-28 > 2024-09-20

### ISSUE THREAD

**Issue by anssiko** [w3c/a11y-request#87]
In the issue title above add the document name followed by the date of this request, then the date of your proposed deadline for comments.

- name of spec to be reviewed: Vibration API
- URL of spec: https://w3c.github.io/vibration/

- Current Rec/Note phase? Recommendation (published under P2015)
- What and when is your next expected transition? Candidate Recommendation Snapshot (see "Other comments")
- What has changed since any previous review?

Please see the [commit history](https://github.com/w3c/vibration/commits/gh-pages/) for details and the [changes section](https://labs.w3.org/spec-generator/?type=respec&url=https%3A%2F%2Fraw.githubusercontent.com%2Fw3c%2Fvibration%2Fchanges%2Findex.html#changes) for an overview of the changes since the latest published version. Diff between the [latest published version](https://www.w3.org/TR/2016/REC-vibration-20161018/) and the [staged snapshot](https://labs.w3.org/spec-generator/?type=respec&url=https%3A%2F%2Fraw.githubusercontent.com%2Fw3c%2Fvibration%2Fchanges%2Findex.html) is available at [htmldiff](https://services.w3.org/htmldiff?doc1=https%3A%2F%2Fwww.w3.org%2FTR%2F2016%2FREC-vibration-20161018%2F&doc2=https%3A%2F%2Flabs.w3.org%2Fspec-generator%2F%3Ftype%3Drespec%26url%3Dhttps%253A%252F%252Fraw.githubusercontent.com%252Fw3c%252Fvibration%252Fchanges%252Findex.html).

- Please point to the results of your [self-review](https://w3c.github.io/apa/fast/checklist.html): https://github.com/w3c/vibration/issues/37
- Where and how to file issues arising? https://github.com/w3c/vibration/issues
- Pointer to any explainer for the spec?
 
This feature predates the explainer era, but its [MDN entry](https://developer.mozilla.org/en-US/docs/Web/API/Vibration_API) serves as a good starting point.

Other comments:

Due to complexity of revising a Recommendation under the old process, TR for this specification did not receive these latest updates informed by implementation experience, but they were incorporated into the Editor's Draft instead. This caused some unfortunate confusion among readers not closely watching the specification. To clear this confusion, supported by reinvigorated interest and process improvements for revising a Recommendation, this API is now being revived on the Recommendation Track to allow bringing the updates from the ED back to TR and to allow for further improvements using the modern streamlined publication flow.

Thank you for your review!

**Comment by anssiko** [comment]
@newtonsgroove, we look forward to your feedback. Our plan is to publish a CRS shortly and we'd be happy to incorporate any accessibility considerations you may have in the CRS, or in a future update if you need more time.

We've received positive feedback from the disabled community for this API as noted in the Accessibility Checklist https://github.com/w3c/vibration/issues/37. That project and context may be of interest to you.

Thank you for your contributions!

**Comment by matatk** [comment]
Hi @anssiko. We discussed the API on our APA WG call today and may have a comment for you next week (if it has consensus). Don't let us hold up publication in the meantime. We look forward to providing input soon, or later on for a future version.

**Comment by anssiko** [comment]
@matatk thanks for confirming this review does not block the CRS publication.

We look forward to integrating a11y considerations into any of the future versions.

**Comment by matatk** [comment]
Hi @anssiko. [We filed an issue](https://github.com/w3c/vibration/issues/50) as the result of our review. I think it's OK to close this thread now, as the other issue will be tracked automatically for us. Thanks for your review request, and we look forward to continuing to work with you.
