### ISSUE TITLE
Guidance on Applying WCAG 2 to Non-Web Information and Communications Technologies (WCAG2ICT) 2024-07-02> 2024-08-06

### ISSUE THREAD

**Issue by daniel-montalvo** [w3c/a11y-request#88]
In the issue title above add the document name followed by the date of this request, then the date of your proposed deadline for comments.

- name of spec to be reviewed: Guidance on Applying WCAG 2 to Non-Web Information and Communications Technologies (WCAG2ICT)
- URL of spec: https://www.w3.org/TR/wcag2ict-22/#sotd

- Current Rec/Note phase? Draft Note
- What and when is your next expected transition? Publish as a W3C Note after Wide review, which ends 6 September 2024
- What has changed since any previous review? Updates since the 15 August 2023 draft include:
  *	Added guidance for WCAG 2.2 success criteria
  *	Addressed comments from the previous draft
  *	Completed the Success Criteria Problematic for Closed Functionality section

- Please point to the results of your [self-review](https://w3c.github.io/apa/fast/checklist.html) NA -- This Note does not create/propose new technologies/accessibility features. Instead, it provides guidance on how WCAG could be applied to other non-Web ICT.
- Where and how to file issues arising? https://www.github.com/w3c/wcag2ict/issues/new
- Pointer to any explainer for the spec? https://www.w3.org/WAI/standards-guidelines/wcag/non-web-ict/

Other comments:

**Comment by matatk** [comment]
We have filed some comments from APA following our review:

* https://github.com/w3c/wcag2ict/issues/464

* https://github.com/w3c/wcag2ict/issues/465

* https://github.com/w3c/wcag2ict/issues/466

**Comment by daniel-montalvo** [comment]
Thank you very much!

 

 

 

--

Daniel Montalvo Charameli

Accessibility Specialist

W3C/WAI
