### ISSUE TITLE
WebAssembly 2024-09-17 > 2024-10-01

### ISSUE THREAD

**Issue by dschuff** [w3c/a11y-request#91]
This is a request for transition for version 2.0 of all 3 WebAssembly specifications, namely the [core](https://www.w3.org/TR/wasm-core-2/) spec, which defines the core code format and semantics;
the [JS API](https://www.w3.org/TR/wasm-js-api-2/) specification, which provides a JavaScript API for interacting with WebAssembly; and the [Web API](https://www.w3.org/TR/wasm-web-api-2/) specification, which describes the integration of WebAssembly with the broader web platform. 

- What and when is your next expected transition? 
CR, as soon as horizontal review is done.

- What has changed since any previous review?
All of the analysis herein concerns the changes made since Wasm 1.0. These are listed
[here](https://www.w3.org/TR/wasm-core-2/#release-20) and include the following extension
proposals:
Sign extension instructions; Non-trapping float-to-int conversions; multi-value block types and function results;
reference types, table instructions, and multiple tables; bulk memory and table instructions; SIMD vector instructions. Links to overviews of each proposal can be found in the proposal's respective github repo (these are listed [here](https://github.com/WebAssembly/proposals?tab=readme-ov-file)). 

- Please point to the results of your own self-review (see https://w3c.github.io/apa/fast/checklist.html)
https://github.com/WebAssembly/spec/issues/1805

- Where and how to file issues arising?
https://github.com/WebAssembly/spec/issues

- Pointer to any explainer for the spec?
There is not an explainer for the entire spec (and in any case it is fairly large). Links to explainers/overviews for each
of the 5 proposals can be found in the proposal's respective github repo (these are listed [here](https://github.com/WebAssembly/proposals?tab=readme-ov-file)). 

Other comments:
Since WebAssembly is a specification for the representation and semantics of computation, it seems there is very little interaction with accessibility principles.

**Comment by dschuff** [comment]
For review convenience, here is a list of the explainers for the proposals that have gone into 2.0, compared to 1.0 (currently in REC state). These are informal descriptions of the proposed changes and are not canonical, but describe an overview of the feature and could be useful in determining whether there is anything of interest for horizontal reviewers.

Note again also that the core spec contains a [list](https://www.w3.org/TR/wasm-core-2/#release-20) of additions since version 1.0 and summarizes the addition to the core spec. The table summarizes the effect on the JS spec. The Web spec is unchanged since 1.0

| Explainer  | Specs affected | JS Spec difference summary |
|----|---|--|
| [Nontrapping float-int conversion](https://github.com/WebAssembly/nontrapping-float-to-int-conversions/blob/main/proposals/nontrapping-float-to-int-conversion/Overview.md) | Core |
| [Sign-extension operators](https://github.com/WebAssembly/sign-extension-ops/blob/master/proposals/sign-extension-ops/Overview.md) | Core |
| [Multi-value block and function returns](https://github.com/WebAssembly/multi-value/blob/master/proposals/multi-value/Overview.md) | Core, JS | Multi-value returns can be passed into JS as JS Arrays |
| [JS BigInt Integration](https://github.com/WebAssembly/JS-BigInt-integration?tab=readme-ov-file) | JS | Wasm i64 values can be passed to and from JS as BigInt values
| [Reference Types](https://github.com/WebAssembly/reference-types/blob/master/proposals/reference-types/Overview.md) | Core, JS | References to JS objects can be passed to and from Wasm as `externref` values.
| [Bulk Memory and table instructions](https://github.com/WebAssembly/bulk-memory-operations/blob/master/proposals/bulk-memory-operations/Overview.md) | Core |
| [SIMD Vector instructions](https://github.com/WebAssembly/simd/blob/main/proposals/simd/SIMD.md) | Core |

**Comment by ruoxiran** [comment]
no comments or requests from APA, thank you.
